import type { InChapterAnchor, ReadingAnchor } from './book/index.js';

/**
 * Minimal key-value storage interface used by reader persistence helpers.
 *
 * Structurally satisfied by the DOM `Storage` objects (`localStorage`,
 * `sessionStorage`), which is the intended default; a host swaps in its own
 * implementation to persist elsewhere. Values are opaque strings produced by
 * {@link serializeReadingPosition} / {@link serializeAnnotations}.
 *
 * Implementations are allowed to throw — private-mode and quota-exhausted
 * browser storage does — and callers in the framework packages catch and degrade
 * to an in-memory copy, so an implementation should not swallow failures itself.
 */
export interface MejiroStorage {
  /**
   * Reads a previously stored value.
   *
   * @param key - Storage key.
   * @returns The stored string, or `null` when the key was never written.
   */
  getItem(key: string): string | null;
  /**
   * Writes a value, replacing any existing one.
   *
   * @param key - Storage key.
   * @param value - Serialized payload.
   * @throws When the backing store rejects the write, e.g. a quota error or
   *   storage disabled by the user agent.
   */
  setItem(key: string, value: string): void;
  /**
   * Deletes a key. Removing a key that was never written is not an error.
   *
   * @param key - Storage key.
   */
  removeItem(key: string): void;
}

/** Persisted reading position. */
export type ReadingPositionValue = ReadingAnchor;

const READING_POSITION_VERSION = 2;

interface PersistedReadingPositionV2 {
  version: 2;
  chapter: number;
  paragraph: number;
  charIndex: number;
}

interface LegacyReadingPositionV1 {
  chapter: number;
  spreadIdx: number;
}

/**
 * Parses current and legacy reading-position payloads.
 *
 * Accepts the versioned envelope written by {@link serializeReadingPosition},
 * the legacy `{ chapter, spreadIdx }` shape, and a bare `ReadingAnchor` object
 * (`{ chapter, paragraph, charIndex }`) — the shape a host gets from stringifying
 * an anchor itself, e.g. when mirroring positions to a server.
 *
 * Returns `null` for anything that is not a well-formed position, including
 * payloads whose `chapter` / `paragraph` / `charIndex` are not non-negative
 * safe integers (fractional, negative, `NaN`, `Infinity` or beyond
 * `Number.MAX_SAFE_INTEGER`), so consumers can index layout data with the
 * returned fields without further checks.
 */
export function parseReadingPosition(raw: string | null): ReadingPositionValue | null {
  if (!raw) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== 'object') return null;
  const p = parsed as Partial<PersistedReadingPositionV2 & LegacyReadingPositionV1>;
  if (!isNonNegativeInteger(p.chapter)) return null;
  if (p.version === READING_POSITION_VERSION) {
    if (!(isNonNegativeInteger(p.paragraph) && isNonNegativeInteger(p.charIndex))) return null;
    return { chapter: p.chapter, paragraph: p.paragraph, charIndex: p.charIndex };
  }
  if (typeof p.spreadIdx === 'number') {
    // biome-ignore lint/suspicious/noConsole: intentional one-time migration notice
    if (typeof console !== 'undefined' && typeof console.warn === 'function') {
      // biome-ignore lint/suspicious/noConsole: intentional one-time migration notice
      console.warn(
        '[mejiro] useReadingPosition: migrating legacy {chapter, spreadIdx} format. ' +
          'spreadIdx has been dropped because it does not survive reflow; the position ' +
          'now resumes at the start of the chapter. Persist new positions via save() to upgrade.',
      );
    }
    return { chapter: p.chapter, paragraph: 0, charIndex: 0 };
  }
  if (
    p.version === undefined &&
    isNonNegativeInteger(p.paragraph) &&
    isNonNegativeInteger(p.charIndex)
  ) {
    return { chapter: p.chapter, paragraph: p.paragraph, charIndex: p.charIndex };
  }
  return null;
}

/** Serializes a reading-position anchor. */
export function serializeReadingPosition(value: ReadingPositionValue): string {
  const payload: PersistedReadingPositionV2 = {
    version: READING_POSITION_VERSION,
    chapter: value.chapter,
    paragraph: value.paragraph,
    charIndex: value.charIndex,
  };
  return JSON.stringify(payload);
}

/**
 * A user-authored annotation on a book.
 *
 * `start` and `end` are reflow-independent: they address paragraph and character
 * offsets rather than page or spread positions, so an annotation survives a font
 * or page-size change. Both anchors are interpreted within `chapter`; an
 * annotation therefore cannot span chapters.
 *
 * {@link parseAnnotations} drops entries that do not match this shape, so any
 * value read back from storage already satisfies the constraints below.
 */
export interface Annotation {
  /**
   * Stable identifier, unique within a book. Generated by
   * {@link createAnnotationId} unless the host assigns its own.
   */
  id: string;
  /** Zero-based chapter index. A non-negative safe integer. */
  chapter: number;
  /** Inclusive start of the annotated range within `chapter`. */
  start: InChapterAnchor;
  /** Exclusive end of the annotated range within `chapter`. */
  end: InChapterAnchor;
  /** Highlight color as a CSS color string. Host-defined; the core never interprets it. */
  color?: string;
  /** Free-form user note attached to the range. */
  note?: string;
  /**
   * Creation time as a millisecond epoch. Only required to be a finite number —
   * it is never used for ordering, which {@link sortAnnotations} derives from the
   * range instead.
   */
  createdAt?: number;
}

const ANNOTATIONS_VERSION = 1;

interface PersistedAnnotations {
  version: number;
  annotations: Annotation[];
}

/**
 * Parses an annotation payload, returning an empty list for invalid data.
 *
 * Accepts the versioned envelope written by {@link serializeAnnotations} and a
 * bare annotation array — the shape a host gets from stringifying the list
 * itself, e.g. when mirroring annotations to a server. Entries that are not
 * well-formed annotations are dropped.
 */
export function parseAnnotations(raw: string | null): Annotation[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw) as Partial<PersistedAnnotations> | unknown[];
    if (Array.isArray(parsed)) return parsed.filter(isAnnotation);
    if (parsed?.version !== ANNOTATIONS_VERSION || !Array.isArray(parsed.annotations)) return [];
    return parsed.annotations.filter(isAnnotation);
  } catch {
    // Bad JSON — treat as empty.
  }
  return [];
}

function isAnnotation(value: unknown): value is Annotation {
  if (!isRecord(value)) return false;
  if (typeof value.id !== 'string' || !isNonNegativeInteger(value.chapter)) return false;
  if (!(isAnchor(value.start) && isAnchor(value.end))) return false;
  if (value.color !== undefined && typeof value.color !== 'string') return false;
  if (value.note !== undefined && typeof value.note !== 'string') return false;
  return value.createdAt === undefined || Number.isFinite(value.createdAt);
}

function isAnchor(value: unknown): value is InChapterAnchor {
  return (
    isRecord(value) &&
    isNonNegativeInteger(value.paragraph) &&
    isNonNegativeInteger(value.charIndex)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isNonNegativeInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0;
}

/** Serializes annotations with a version envelope. */
export function serializeAnnotations(annotations: readonly Annotation[]): string {
  const payload: PersistedAnnotations = {
    version: ANNOTATIONS_VERSION,
    annotations: [...annotations],
  };
  return JSON.stringify(payload);
}

/** Sorts annotations by chapter, paragraph, then character index. */
export function sortAnnotations(annotations: readonly Annotation[]): Annotation[] {
  return [...annotations].sort((a, b) => {
    if (a.chapter !== b.chapter) return a.chapter - b.chapter;
    if (a.start.paragraph !== b.start.paragraph) return a.start.paragraph - b.start.paragraph;
    return a.start.charIndex - b.start.charIndex;
  });
}

/** Creates a best-effort stable client-side annotation id. */
export function createAnnotationId(): string {
  if (
    typeof globalThis.crypto !== 'undefined' &&
    typeof globalThis.crypto.randomUUID === 'function'
  ) {
    return globalThis.crypto.randomUUID();
  }
  return `ann-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}
