name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --run

      - name: Benchmark
        run: yarn bench
